const constants = {
	FETCH_APPOINTMENTS: "FETCH_APPOINTMENTS",
	ADD_APPOINTMENT: "ADD_APPOINTMENT",
	REMOVE_APPOINTMENT: "REMOVE_APPOINTMENT",
	SEARCH_APPOINTMENT: "SEARCH_APPOINTMENT"
}

export default constants