const constants = {
	TOGGLE_ADD_FORM: "TOGGLE_ADD_FORM",
	ADD_ERROR: "ADD_ERROR",
	REMOVE_ERROR: "REMOVE_ERROR",
	TOGGLE_ERROR_MESSAGES: "TOGGLE_ERROR_MESSAGES",
	FETCH_APPOINTMENTS: "FETCH_APPOINTMENTS",
	ADD_APPOINTMENT: "ADD_APPOINTMENT",
	REMOVE_APPOINTMENT: "REMOVE_APPOINTMENT",
	SEARCH_APPOINTMENT: "SEARCH_APPOINTMENT",
	SET_ORDER_BY: "SET_ORDER_BY",
	SET_ORDER_DIR: "SET_ORDER_DIR",
	SET_QUERY_TEXT: "SET_QUERY_TEXT"
}

export default constants